name: Docker Image CI (PR)

on: 
  pull_request:
    branches: 
      - master

env:
  GITHUB_USER: ${{ secrets.GH_USER }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:

  build-docker:
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2

    - run: "yes"



